apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: quickstart
spec:
  count: 1
  elasticsearchRef:
    name: quickstart
  config:
    server.host: "0.0.0.0"  
    xpack.security.enabled: false  
    xpack.security.http.ssl.enabled: false  
    xpack.security.encryptionKey: "a9f8c2e4d6b7f1e9c0a3b5d6e2f9a1b0"
    xpack.reporting.encryptionKey: "1f2e3d4c5b6a7980a1b2c3d4e5f60789"
    xpack.encryptedSavedObjects.encryptionKey: "abcdef0123456789abcdef0123456789"
    elasticsearch.hosts: ["http://elasticsearch-master:9200"]  
    elasticsearch.ssl.verificationMode: "none" 