elasticsearchHosts: "http://elasticsearch:9200"

replicas: 1

service:
  type: NodePort
  ports:
    - name: http
      port: 5601
      targetPort: 5601
      nodePort: 32056

resources:
  requests:
    memory: "2Gi"
    cpu: "1000m"
  limits:
    memory: "4Gi"
    cpu: "2000m"

extraEnvs:
  - name: SERVER_MAXPAYLOAD
    value: "50mb"
  - name: ELASTICSEARCH_REQUESTTIMEOUT
    value: "200000"

extraObjects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: elasticsearch-master-certs
      namespace: elastic-system
    type: Opaque
    data: {}